//products
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const GET_UPDATE_PRODUCT_DATA = 'GET_UPDATE_PRODUCT_DATA';
export const CLEAN_UPDATE_PRODUCT_DATA = 'CLEAN_UPDATE_PRODUCT_DATA';
